# Generated by Django 4.2.8 on 2023-12-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("EntryDate", models.DateField()),
                ("PatientID", models.PositiveIntegerField()),
                ("PatientName", models.CharField(max_length=20)),
                ("Sex", models.CharField(max_length=1)),
                ("DOB", models.DateField()),
                ("HospitalVisited", models.CharField(max_length=20)),
                ("Illness", models.CharField(max_length=20)),
                ("MedicalTest", models.CharField(max_length=20)),
                ("Treatment", models.TextField()),
                ("Contact", models.PositiveIntegerField()),
                ("Address", models.CharField(max_length=20)),
            ],
        ),
    ]
