# Generated by Django 4.2.8 on 2023-12-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TMH", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patients",
            name="Treatment",
            field=models.CharField(max_length=20),
        ),
    ]
